import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// RootLayout is the enter point of app
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Layout file defines basic structure of page */}
        <h1>Page Header</h1>
        {/* children is the JSX return from page.js */}
        {children}
        <h1>Page Footer</h1>
      </body>
    </html>
  )
}
